import '../models/house.dart';

/// Provides house listing data for the application.
///
/// Currently returns mock data so the UI can be developed and tested
/// independently of a running backend. Future iterations will replace
/// this with actual HTTP calls to the Rust API.
class HouseService {
  /// Simulate a network request to fetch all house listings.
  static Future<List<House>> getHouses() async {
    // Simulate network latency for realistic loading state testing.
    await Future.delayed(const Duration(milliseconds: 800));

    return const [
      House(
        id: 1,
        title: 'Modern 3-Bedroom Apartment in Bastos',
        description:
            'Spacious apartment with modern finishes, secure parking, and 24/7 water supply. Located in the upscale Bastos neighborhood, close to embassies and international schools.',
        price: 450000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 140,
        propertyType: 'apartment',
        address: 'Rue 1.123, Bastos',
        city: 'Yaoundé',
        state: 'Centre',
        zipCode: '12345',
        country: 'Cameroon',
        latitude: 3.8480,
        longitude: 11.5021,
        landlordPhone: '+237674123456',
      ),
      House(
        id: 2,
        title: 'Affordable Studio near University of Yaoundé I',
        description:
            'Compact studio ideal for students. Shared kitchen and bathroom. Walking distance to campus and affordable restaurants.',
        price: 75000,
        bedrooms: 1,
        bathrooms: 1,
        squareFeet: 35,
        propertyType: 'studio',
        address: 'Ngoa-Ekelle, Campus Road',
        city: 'Yaoundé',
        state: 'Centre',
        zipCode: '12346',
        country: 'Cameroon',
        latitude: 3.8600,
        longitude: 11.5100,
        landlordPhone: '+237675234567',
      ),
      House(
        id: 3,
        title: 'Family House in Bonapriso',
        description:
            'Beautiful family home with a small garden, tiled floors, and independent water tank. Quiet street with friendly neighbors.',
        price: 380000,
        bedrooms: 4,
        bathrooms: 2.5,
        squareFeet: 200,
        propertyType: 'house',
        address: 'Avenue de Gaulle, Bonapriso',
        city: 'Douala',
        state: 'Littoral',
        zipCode: '23456',
        country: 'Cameroon',
        latitude: 4.0500,
        longitude: 9.7000,
        landlordPhone: '+237676345678',
      ),
      House(
        id: 4,
        title: 'Furnished 2-Bedroom Flat in Akwa',
        description:
            'Fully furnished flat in the commercial heart of Douala. Close to banks, supermarkets, and public transport. Air conditioning in both bedrooms.',
        price: 250000,
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: 90,
        propertyType: 'apartment',
        address: 'Boulevard de la Liberté, Akwa',
        city: 'Douala',
        state: 'Littoral',
        zipCode: '23457',
        country: 'Cameroon',
        latitude: 4.0430,
        longitude: 9.6940,
        landlordPhone: '+237677456789',
      ),
      House(
        id: 5,
        title: 'Cozy 1-Bedroom in Buea Town',
        description:
            'Clean one-bedroom apartment with uninterrupted mountain views. Reliable electricity and good internet coverage. Ideal for young professionals.',
        price: 120000,
        bedrooms: 1,
        bathrooms: 1,
        squareFeet: 55,
        propertyType: 'apartment',
        address: 'Great Soppo, Buea Town',
        city: 'Buea',
        state: 'Southwest',
        zipCode: '34567',
        country: 'Cameroon',
        latitude: 4.1520,
        longitude: 9.2900,
        landlordPhone: '+237678567890',
      ),
      House(
        id: 6,
        title: '4-Bedroom Villa in Limbe Beachside',
        description:
            'Stunning villa with ocean views, large compound, and parking for multiple cars. Perfect for families or expats. 5 minutes walk to the beach.',
        price: 600000,
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: 280,
        propertyType: 'house',
        address: 'Down Beach Road, Limbe',
        city: 'Limbe',
        state: 'Southwest',
        zipCode: '34568',
        country: 'Cameroon',
        latitude: 4.0240,
        longitude: 9.1900,
        landlordPhone: '+237679678901',
      ),
      House(
        id: 7,
        title: 'Traditional 3-Bedroom House in Bamenda',
        description:
            'Solid brick house in a calm neighborhood near Mile 2. Large living room, functional kitchen, and strong community security.',
        price: 180000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 150,
        propertyType: 'house',
        address: 'Mile 2, Nkwen',
        city: 'Bamenda',
        state: 'Northwest',
        zipCode: '45678',
        country: 'Cameroon',
        latitude: 6.0000,
        longitude: 10.1500,
        landlordPhone: '+237680789012',
      ),
      House(
        id: 8,
        title: 'Student Hostel near UB Buea',
        description:
            'Shared hostel with private rooms. Common study area, generator backup, and gated compound. Popular with University of Buea students.',
        price: 60000,
        bedrooms: 1,
        bathrooms: 1,
        squareFeet: 25,
        propertyType: 'hostel',
        address: 'Molyko, UB Junction',
        city: 'Buea',
        state: 'Southwest',
        zipCode: '34569',
        country: 'Cameroon',
        latitude: 4.1550,
        longitude: 9.2950,
        landlordPhone: '+237681890123',
      ),
      House(
        id: 9,
        title: 'Luxury Apartment in Deido',
        description:
            'High-end apartment with marble floors, modern kitchen, and secured elevator access. Close to Douala International Airport.',
        price: 500000,
        bedrooms: 3,
        bathrooms: 2.5,
        squareFeet: 160,
        propertyType: 'apartment',
        address: 'Rue Kotto, Deido',
        city: 'Douala',
        state: 'Littoral',
        zipCode: '23458',
        country: 'Cameroon',
        latitude: 4.0550,
        longitude: 9.7650,
        landlordPhone: '+237682901234',
      ),
      House(
        id: 10,
        title: 'Compact Shop-House in Kumba Market',
        description:
            'Ground floor shop with residential space above. High foot traffic area ideal for small business owners.',
        price: 150000,
        bedrooms: 2,
        bathrooms: 1.5,
        squareFeet: 80,
        propertyType: 'house',
        address: 'Kumba Main Market Road',
        city: 'Kumba',
        state: 'Southwest',
        zipCode: '34570',
        country: 'Cameroon',
        latitude: 4.6360,
        longitude: 9.4450,
        landlordPhone: '+237683012345',
      ),
      House(
        id: 11,
        title: 'Newly Built 2-Bedroom in Mokolo',
        description:
            'Brand new construction with modern fittings, tiled bathrooms, and running water. Good road access and close to the market.',
        price: 130000,
        bedrooms: 2,
        bathrooms: 1,
        squareFeet: 75,
        propertyType: 'apartment',
        address: 'Mokolo Market Street',
        city: 'Yaoundé',
        state: 'Centre',
        zipCode: '12347',
        country: 'Cameroon',
        latitude: 3.8700,
        longitude: 11.5150,
        landlordPhone: '+237684123456',
      ),
      House(
        id: 12,
        title: 'Rural Homestead in Bafoussam',
        description:
            'Large family compound on a quiet hillside. Multiple buildings, outdoor kitchen, and ample farmland space. Great for extended families.',
        price: 220000,
        bedrooms: 5,
        bathrooms: 3,
        squareFeet: 300,
        propertyType: 'house',
        address: 'Bamendjing Road, Bafoussam',
        city: 'Bafoussam',
        state: 'West',
        zipCode: '56789',
        country: 'Cameroon',
        latitude: 5.4700,
        longitude: 10.4200,
        landlordPhone: '+237685234567',
      ),
      House(
        id: 13,
        title: 'Executive Flat in Ngousso',
        description:
            'Executive flat in a gated compound. Close to government ministries and the Prime Minister\'s office. Excellent security and water supply.',
        price: 350000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 130,
        propertyType: 'apartment',
        address: 'Rue du Ministère, Ngousso',
        city: 'Yaoundé',
        state: 'Centre',
        zipCode: '12348',
        country: 'Cameroon',
        latitude: 3.8650,
        longitude: 11.5100,
        landlordPhone: '+237686345678',
      ),
      House(
        id: 14,
        title: 'Simple 2-Bedroom in Maroua',
        description:
            'Affordable housing in a hot climate city. Thick walls keep interiors cool. Close to the central market and hospital.',
        price: 90000,
        bedrooms: 2,
        bathrooms: 1,
        squareFeet: 70,
        propertyType: 'house',
        address: 'Rue de l\'Hopital, Maroua',
        city: 'Maroua',
        state: 'Far-North',
        zipCode: '67890',
        country: 'Cameroon',
        latitude: 10.5910,
        longitude: 14.3150,
        landlordPhone: '+237687456789',
      ),
      House(
        id: 15,
        title: 'Spacious Duplex in Bonanjo',
        description:
            'Two-story duplex with a rooftop terrace, large living area, and servant quarters. Located in Douala\'s administrative district.',
        price: 700000,
        bedrooms: 5,
        bathrooms: 3.5,
        squareFeet: 250,
        propertyType: 'house',
        address: 'Avenue du Général de Gaulle, Bonanjo',
        city: 'Douala',
        state: 'Littoral',
        zipCode: '23459',
        country: 'Cameroon',
        latitude: 4.0460,
        longitude: 9.6900,
        landlordPhone: '+237688567890',
      ),
      House(
        id: 16,
        title: 'Garden Flat in Ngaoundéré',
        description:
            'Ground floor flat with a private garden and fruit trees. Cool highland climate, reliable water, and friendly neighborhood.',
        price: 160000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 110,
        propertyType: 'apartment',
        address: 'Mardock Avenue, Ngaoundéré',
        city: 'Ngaoundéré',
        state: 'Adamawa',
        zipCode: '78901',
        country: 'Cameroon',
        latitude: 7.3200,
        longitude: 13.5800,
        landlordPhone: '+237689678901',
      ),
      House(
        id: 17,
        title: 'Single Room in Obili',
        description:
            'Basic single room with shared toilet and bathroom. Very affordable, close to student nightlife and cheap food.',
        price: 40000,
        bedrooms: 1,
        bathrooms: 0.5,
        squareFeet: 20,
        propertyType: 'room',
        address: 'Obili, Yaoundé',
        city: 'Yaoundé',
        state: 'Centre',
        zipCode: '12349',
        country: 'Cameroon',
        latitude: 3.8550,
        longitude: 11.5050,
        landlordPhone: '+237690789012',
      ),
      House(
        id: 18,
        title: '3-Bedroom Bungalow in Garoua',
        description:
            'Single-story bungalow with a large yard, mango trees, and a borehole. Perfect for families seeking space and privacy.',
        price: 200000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 160,
        propertyType: 'house',
        address: 'Rue de l\'Université, Garoua',
        city: 'Garoua',
        state: 'North',
        zipCode: '89012',
        country: 'Cameroon',
        latitude: 9.3000,
        longitude: 13.4000,
        landlordPhone: '+237691890123',
      ),
      House(
        id: 19,
        title: 'Penthouse in Bali',
        description:
            'Top-floor penthouse with panoramic views of Yaoundé. Private elevator, marble floors, and integrated smart home features.',
        price: 850000,
        bedrooms: 4,
        bathrooms: 3.5,
        squareFeet: 220,
        propertyType: 'apartment',
        address: 'Bali, Yaoundé',
        city: 'Yaoundé',
        state: 'Centre',
        zipCode: '12350',
        country: 'Cameroon',
        latitude: 3.8800,
        longitude: 11.4900,
        landlordPhone: '+237692901234',
      ),
      House(
        id: 20,
        title: '2-Bedroom Apartment in Bafut',
        description:
            'Newly renovated apartment with good road access. Close to the palace and local market. Ideal for small families.',
        price: 110000,
        bedrooms: 2,
        bathrooms: 1,
        squareFeet: 65,
        propertyType: 'apartment',
        address: 'Bafut Palace Road',
        city: 'Bamenda',
        state: 'Northwest',
        zipCode: '45679',
        country: 'Cameroon',
        latitude: 6.0800,
        longitude: 10.1000,
        landlordPhone: '+237693012345',
      ),
      House(
        id: 21,
        title: 'Commercial House in Makepe',
        description:
            'Mixed-use building with a shop on the ground floor and 3 bedrooms upstairs. Great for entrepreneurs who want to live above their business.',
        price: 280000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 140,
        propertyType: 'house',
        address: 'Makepe Missoke, Douala',
        city: 'Douala',
        state: 'Littoral',
        zipCode: '23460',
        country: 'Cameroon',
        latitude: 4.0950,
        longitude: 9.7650,
        landlordPhone: '+237694123456',
      ),
      House(
        id: 22,
        title: 'Eco-Friendly House in Buea',
        description:
            'Solar-powered house with rainwater harvesting and organic garden. Modern design with natural ventilation. Popular with environmentally conscious tenants.',
        price: 320000,
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: 145,
        propertyType: 'house',
        address: 'Clerks Quarter, Buea',
        city: 'Buea',
        state: 'Southwest',
        zipCode: '34571',
        country: 'Cameroon',
        latitude: 4.1600,
        longitude: 9.2800,
        landlordPhone: '+237695234567',
      ),
    ];
  }
}
